-- Run as the PAYPILOT schema owner.
CREATE SEQUENCE PAYMENT_RECORD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PAYMENT_RECORD (
 ID NUMBER(19) NOT NULL, USER_ID VARCHAR2(100 CHAR) NOT NULL,
 BILL_CATEGORY VARCHAR2(60 CHAR) NOT NULL, BILL_NAME VARCHAR2(160 CHAR) NOT NULL,
 TOTAL_AMOUNT NUMBER(19,2) NOT NULL, PAID_AMOUNT NUMBER(19,2) DEFAULT 0 NOT NULL,
 FEE_AMOUNT NUMBER(19,2) DEFAULT 0 NOT NULL, DUE_DATE DATE NOT NULL,
 PAID_AT TIMESTAMP NULL, PAYMENT_METHOD VARCHAR2(60 CHAR) NULL,
 CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
 CONSTRAINT PK_PAYMENT_RECORD PRIMARY KEY(ID),
 CONSTRAINT CK_PAYMENT_TOTAL CHECK(TOTAL_AMOUNT >= 0),
 CONSTRAINT CK_PAYMENT_PAID CHECK(PAID_AMOUNT >= 0 AND PAID_AMOUNT <= TOTAL_AMOUNT),
 CONSTRAINT CK_PAYMENT_FEE CHECK(FEE_AMOUNT >= 0));
CREATE INDEX IX_PAYMENT_USER_DUE ON PAYMENT_RECORD(USER_ID,DUE_DATE);
CREATE INDEX IX_PAYMENT_USER_CATEGORY ON PAYMENT_RECORD(USER_ID,BILL_CATEGORY);
